version: "3" # composeファイルのバージョン
services:
  java: # サービス名
    build: ./docker/java # ビルドに使うDockerfileの場所
    tty: true # コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる 
      - 8080:8080
    volumes:
      - ./server/src:/usr/src:cached